import telebot
import webbrowser
from telebot import types

bot = telebot.TeleBot('6852765060:AAG67TGxzWqhSfi6UYjriF-Z9CwjHDO_Yy4')



@bot.message_handler(commands=['start'])
def start(message):
   detali = types.ReplyKeyboardMarkup()
   b2 = types.KeyboardButton('Программируемый блок EV3')
   detali.row(b2)
   b3 = types.KeyboardButton('Моторы')
   b4 = types.KeyboardButton('Датчики')
   detali.row(b3,b4)
   code = types.ReplyKeyboardMarkup()
   b10 = types.KeyboardButton('Начало кода')
   b11 = types.KeyboardButton('Управление моторами')
   code.row(b10,b11)
   b12 = types.KeyboardButton('Управление датчиками')
   b13 = types.KeyboardButton('Визуальные эффекты')
   code.row(b12,b13)
   start = types.ReplyKeyboardMarkup()
   b7 = types.KeyboardButton('Детали ⚙️')
   start.row(b7)
   b8 = types.KeyboardButton('Программирование 💻')
   start.row(b8)
   b9 = types.KeyboardButton('Помощь❓')
   start.row(b9)
   bremove = types.ReplyKeyboardRemove()
   bot.send_message(message.chat.id, "LEGO MINDSTORMS – это конструкторский набор программируемой робототехники, который даёт возможность создавать собственных роботов LEGO и управлять ими. \nИзучайте LEGO Mindstorms с помощью нашего бота!", reply_markup=start)
   bot.register_next_step_handler(message, on_click)

def on_click(message):
   detali = types.ReplyKeyboardMarkup()
   b2 = types.KeyboardButton('Программируемый блок EV3')
   detali.row(b2)
   b3 = types.KeyboardButton('Моторы')
   b4 = types.KeyboardButton('Датчики')
   detali.row(b3,b4)
   code = types.ReplyKeyboardMarkup()
   b10 = types.KeyboardButton('Начало кода')
   b11 = types.KeyboardButton('Управление моторами')
   code.row(b10,b11)
   b12 = types.KeyboardButton('Управление датчиками')
   b13 = types.KeyboardButton('Визуальные эффекты')
   code.row(b12,b13)
   start = types.ReplyKeyboardMarkup()
   b7 = types.KeyboardButton('Детали ⚙️')
   start.row(b7)
   b8 = types.KeyboardButton('Программирование 💻')
   start.row(b8)
   b9 = types.KeyboardButton('Помощь❓')
   start.row(b9)
   bremove = types.ReplyKeyboardRemove()
   if message.text == "/start":
       bot.send_message(message.chat.id,'LEGO MINDSTORMS – это конструкторский набор программируемой робототехники, который даёт возможность создавать собственных роботов LEGO и управлять ими. \nИзучайте LEGO Mindstorms с помощью нашего бота! \nДетали - объяснение функционала деталей \nПрограммирование - объяснение программирования \nСайт - оффициальный сайт', reply_markup=start)
       bot.register_next_step_handler(message, on_click)
   elif message.text == "Детали ⚙️":
       bot.send_message(message.chat.id,'Вы выбрали раздел Детали⚙️. Теперь выберите с чем именно вы хотите познакомится - ',reply_markup=detali)
       bot.register_next_step_handler(message, on_click1)
   elif message.text == "Программирование 💻":
       bot.send_message(message.chat.id,'Вы выбрали раздел Программирование💻', reply_markup=code)
       bot.register_next_step_handler(message, on_click2)
   elif message.text == "Помощь❓":
       bot.send_message(message.chat.id, 'Для взаимодействия с ботом выберите - \nДетали - объяснение функционала деталей \nПрограммирование - объяснение программирования \nСайт - оффициальный сайт', reply_markup=start)
       bot.register_next_step_handler(message, on_click)
   elif message.text != "Детали ⚙️" or "Программирование 💻" or "Помощь❓":
       bot.send_message(message.chat.id,'я не воспринимаю данный вариант ответа', reply_markup=start)
       bot.register_next_step_handler(message, on_click)


@bot.message_handler(commands=['detali'])
def detali(message):
   detali = types.ReplyKeyboardMarkup()
   b2 = types.KeyboardButton('Программируемый блок EV3')
   detali.row(b2)
   b3 = types.KeyboardButton('Моторы')
   b4 = types.KeyboardButton('Датчики')
   detali.row(b3,b4)
   code = types.ReplyKeyboardMarkup()
   b10 = types.KeyboardButton('Начало кода')
   b11 = types.KeyboardButton('Управление моторами')
   code.row(b10,b11)
   b12 = types.KeyboardButton('Управление датчиками')
   b13 = types.KeyboardButton('Визуальные эффекты')
   code.row(b12,b13)
   start = types.ReplyKeyboardMarkup()
   b7 = types.KeyboardButton('Детали ⚙️')
   start.row(b7)
   b8 = types.KeyboardButton('Программирование 💻')
   start.row(b8)
   b9 = types.KeyboardButton('Помощь❓')
   start.row(b9)
   bremove = types.ReplyKeyboardRemove()
   bot.send_message(message.chat.id, "Детали конструктора LEGO Mindstorms - ", reply_markup=detali)
   bot.register_next_step_handler(message, on_click)
   bot.register_next_step_handler(message, on_click1)

def on_click1(message):
   detali = types.ReplyKeyboardMarkup()
   b2 = types.KeyboardButton('Программируемый блок EV3')
   detali.row(b2)
   b3 = types.KeyboardButton('Моторы')
   b4 = types.KeyboardButton('Датчики')
   detali.row(b3,b4)
   code = types.ReplyKeyboardMarkup()
   b10 = types.KeyboardButton('Начало кода')
   b11 = types.KeyboardButton('Управление моторами')
   code.row(b10,b11)
   b12 = types.KeyboardButton('Управление датчиками')
   b13 = types.KeyboardButton('Визуальные эффекты')
   code.row(b12,b13)
   start = types.ReplyKeyboardMarkup()
   b7 = types.KeyboardButton('Детали ⚙️')
   start.row(b7)
   b8 = types.KeyboardButton('Программирование 💻')
   start.row(b8)
   b9 = types.KeyboardButton('Помощь❓')
   start.row(b9)
   bremove = types.ReplyKeyboardRemove()
   ev3 = open("C:/Users/thefr/OneDrive/Рабочий стол/GuideLegoMindStorms/telegrambot/pitanie.png", "rb")
   motor1 = open("C:/Users/thefr/OneDrive/Рабочий стол/GuideLegoMindStorms/telegrambot/мотор.png", "rb")
   motor2 = open("C:/Users/thefr/OneDrive/Рабочий стол/GuideLegoMindStorms/telegrambot/слабыймотор.png", "rb")
   button = open("C:/Users/thefr/OneDrive/Рабочий стол/GuideLegoMindStorms/telegrambot/кнопка.png", "rb")
   ik = open("C:/Users/thefr/OneDrive/Рабочий стол/GuideLegoMindStorms/telegrambot/ИК.png", "rb")
   ultra = open("C:/Users/thefr/OneDrive/Рабочий стол/GuideLegoMindStorms/telegrambot/ультразв.png", "rb")
   color = open("C:/Users/thefr/OneDrive/Рабочий стол/GuideLegoMindStorms/telegrambot/цвет.png", "rb")
   povorot = open("C:/Users/thefr/OneDrive/Рабочий стол/GuideLegoMindStorms/telegrambot/поворот.png", "rb")
   if message.text == "Программируемый блок EV3":
       bot.send_message(message.chat.id, "Все моторы и датчики подключаются к данному блоку. Он подключается к компьютеру или телефону и программируется. Заряжается от специального блока питания. Имеет 8 разьемов, 4 разьема под моторы и 4 под датчики", reply_markup=start)
       bot.send_photo(message.chat.id, ev3)
       bot.register_next_step_handler(message, on_click)
   elif message.text == "Моторы":
       bot.send_message(message.chat.id, "В стандартном комплекте есть 3 мотора.", reply_markup=start)
       bot.send_message(message.chat.id,  "2 из них являются большими моторами.", reply_markup=start)
       bot.send_photo(message.chat.id, motor1)
       bot.send_message(message.chat.id,  "1 из них средний мотор.", reply_markup=start)
       bot.send_photo(message.chat.id, motor2)
       bot.send_message(message.chat.id,  "Подключается к Программируемому блоку EV3 к разьемам N-N. Можно задавать: Скорость в %, Количество оборотов, Задавать время работы, поворачивать робота влево и вправо, и еще много другого!", reply_markup=start)
       bot.register_next_step_handler(message, on_click)
   elif message.text == "Датчики":
       bot.send_message(message.chat.id, "С помощью датчиков мы можем настроить как именно будет работать робот. Например робот будет ехать в перед при нажатие на кнопку. Есть 5 датчиков - ", reply_markup=start)
       bot.send_message(message.chat.id, "Датчик  касания", reply_markup=start)
       bot.send_photo(message.chat.id, button)
       bot.send_message(message.chat.id, "Датчик  цвета", reply_markup=start)
       bot.send_photo(message.chat.id, color)
       bot.send_message(message.chat.id, "ИК-датчик", reply_markup=start)
       bot.send_photo(message.chat.id, ik)
       bot.send_message(message.chat.id, "Ультразвуковой датчик", reply_markup=start)
       bot.send_photo(message.chat.id, ultra)
       bot.send_message(message.chat.id, "Гироскопический  касания", reply_markup=start)
       bot.send_photo(message.chat.id, povorot)
       bot.send_message(message.chat.id, "Датчик касания - это кнопка при нажатие на которую или при отпускании которой будет производится действие которое будет прописано в коде. \nГироскопический датчик - измеряет вращательное движение робота и изменение его положения.Гироскопический датчик предназначен для измерения угла вращения робота или скорости вращения. \nДатчик цвета - при обноружении нужного цвета или нужной яркости будет запускаться часть кода где мы используем датчик цвета. Например при обноружении черного цвета ехать назад. \nУльтра звуковой датчик - датчик измеряет раасстояние до объекта, и в зависимости от дальности объекта будет работать нужная часть кода \nИК-датчик - это датчик, который предназначен для считывания определенной информации об окружающей среде за счет испускания и приема инфракрасного излучения.", reply_markup=start)
       bot.register_next_step_handler(message, on_click)
   elif message.text != "Программируемый блок EV3" or "Моторы" or "Датчики" or "/start":
       bot.send_message(message.chat.id,'я не воспринимаю данный вариант ответа', reply_markup=start)
       bot.register_next_step_handler(message, on_click)

@bot.message_handler(commands=['code'])
def code(message):
   detali = types.ReplyKeyboardMarkup()
   b2 = types.KeyboardButton('Программируемый блок EV3')
   detali.row(b2)
   b3 = types.KeyboardButton('Моторы')
   b4 = types.KeyboardButton('Датчики')
   detali.row(b3,b4)
   code = types.ReplyKeyboardMarkup()
   b10 = types.KeyboardButton('Начало кода')
   b11 = types.KeyboardButton('Управление моторами')
   code.row(b10,b11)
   b12 = types.KeyboardButton('Управление датчиками')
   b13 = types.KeyboardButton('Визуальные эффекты')
   code.row(b12,b13)
   start = types.ReplyKeyboardMarkup()
   b7 = types.KeyboardButton('Детали ⚙️')
   start.row(b7)
   b8 = types.KeyboardButton('Программирование 💻')
   start.row(b8)
   b9 = types.KeyboardButton('Помощь❓')
   start.row(b9)
   bremove = types.ReplyKeyboardRemove()
   bot.send_message(message.chat.id, "Программирование Lego MINDSTORMS - ", reply_markup=code)
   bot.register_next_step_handler(message, on_click2)

def on_click2(message):
   detali = types.ReplyKeyboardMarkup()
   b2 = types.KeyboardButton('Программируемый блок EV3')
   detali.row(b2)
   b3 = types.KeyboardButton('Моторы')
   b4 = types.KeyboardButton('Датчики')
   detali.row(b3,b4)
   code = types.ReplyKeyboardMarkup()
   b10 = types.KeyboardButton('Начало кода')
   b11 = types.KeyboardButton('Управление моторами')
   code.row(b10,b11)
   b12 = types.KeyboardButton('Управление датчиками')
   b13 = types.KeyboardButton('Визуальные эффекты')
   code.row(b12,b13)
   start = types.ReplyKeyboardMarkup()
   b7 = types.KeyboardButton('Детали ⚙️')
   start.row(b7)
   b8 = types.KeyboardButton('Программирование 💻')
   start.row(b8)
   b9 = types.KeyboardButton('Помощь❓')
   start.row(b9)
   bremove = types.ReplyKeyboardRemove()
   if message.text == "Начало кода":
       bot.send_message(message.chat.id, "Начинать код нужно с блока который будет запускать код. Их есть 5: Первое - код запускается сразу после его запуска на роботе, Второе - когда датчик цвета видит определный цвет, Третий - когда кнопка нажата, Четвертый - когда угол менее, больше или равно определенному углу, Пятый - когда цвентральная кнопка на блоке EV3 нажата.", reply_markup=start)
       bot.register_next_step_handler(message, on_click)
   elif message.text == "Управление моторами":
       bot.send_message(message.chat.id, "Моторами можно управлять по разному. Можно перемещать по часовой и против часовой на n-количество оборотов или секунд, можно его просто запустить без точного количества действий, можно остановить, устновить скорость в % для моторов, и можно задавать количество оборотов со определенной скоростью", reply_markup=start)
       bot.register_next_step_handler(message, on_click)
   elif message.text == "Управление датчиками":
       bot.send_message(message.chat.id, "С помощью датчиков мы можем делать интересные программы. Управлять датчиками мы можем с помощью двух разделов в программе EV3 Classroom это разделы датчики и операторы. Для чего нужен раздел датчики понятно из названия, а раздел операторы нужны для задования условий. Например ехать назад если яроксть меньше 20%(для этого используется датчик цвета).", reply_markup=start)
       bot.register_next_step_handler(message, on_click)
   elif message.text == "Визуальные эффекты":
       bot.send_message(message.chat.id, "Если визуальные эффекты как - настройка дисплея и звука. В EV3 Classroom есть разделы - Дисплей и Звук. Благодоря ним мы можем отображать лицо на Программируемом блоке EV3 а также чтобы он издавал звуки при необходимых условиях.", reply_markup=start)
       bot.register_next_step_handler(message, on_click)
   elif message.text != "Начало кода" or "Управление моторами" or "Визуальные эффекты" or "Управление датчиками" or "/start":
       bot.send_message(message.chat.id,'я не воспринимаю данный вариант ответа', reply_markup=start)
       bot.register_next_step_handler(message, on_click)

bot.polling(none_stop=True)